import 'package:chat_app/domain/entities/chat_message.dart';

final exampleData = [
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
  ChatMessage(
    message: 'In tempus mauris at velit egestas, sed blandit felis ultrices.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Ut molestie mauris et ligula finibus iaculis.',
    author: 'You',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: true,
  ),
  ChatMessage(
    message: 'Sed a tempor ligula.',
    author: 'Ivan Petrov',
    messageDate: DateTime.now(),
    isRead: true,
    isMine: false,
  ),
];
